name: rnote
base: core22
adopt-info: rnote
license: GPL-3.0+
issues: https://github.com/soumyaDghosh/rnote-snap/issues
source-code: https://github.com/flxzt/rnote
website: https://github.com/soumyaDghosh/rnote-snap
architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable
confinement: strict
compression: lzo

parts:
  rustup:
    plugin: rust
    source: .
    rust-channel: "1.76"
    override-build: ""
    override-prime: ""

  rnote:
    after: [rustup]
    plugin: meson
    source: https://github.com/flxzt/rnote.git
    source-tag: 'v0.10.1'
    source-depth: 1
    build-environment:
      - PATH: ${HOME}/.cargo/bin:${PATH}
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    build-packages:
      - libasound2-dev
      - clang
    build-snaps:
      - cmake
    meson-parameters:
      - --prefix=/snap/rnote/current/usr
    organize:
      snap/rnote/current/usr: usr
    parse-info:
      - usr/share/metainfo/com.github.flxzt.rnote.metainfo.xml

slots:
  rnote:
    interface: dbus
    bus: session
    name: com.github.flxzt.rnote

apps:
  rnote:
    command: usr/bin/rnote
    extensions: [gnome]
    common-id: com.github.flxzt.rnote
    plugs:
      - home
      - removable-media
