name: rnote # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: rnote
license: GPL-3.0+
issues: https://github.com/soumyaDghosh/rnote-snap/issues
source-code: https://github.com/flxzt/rnote
website: https://github.com/soumyaDghosh/rnote-snap
architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
compression: lzo

parts:
  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: |
      echo 'Skip Prime'
  rnote:
    after: [rustup]
    # See 'snapcraft plugins'
    plugin: meson
    source: https://github.com/flxzt/rnote.git
    source-tag: v0.7.1
    source-depth: 1
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    build-packages:
      - cmake
      - libasound2-dev
      - clang
    meson-parameters:
      - --prefix=/snap/rnote/current/usr
    organize:
      snap/rnote/current/usr: usr
    parse-info:
      - usr/share/metainfo/com.github.flxzt.rnote.metainfo.xml
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - rnote
      - rustup
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - gnome-42-2204
      - gtk-common-themes
      - core22
    override-prime: |
      set -eux
      for snap in "gnome-42-2204" "gtk-common-themes" "core22"; do
      cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done

slots:
  rnote:
    interface: dbus
    bus: session
    name: com.github.flxzt.rnote
apps:
  rnote:
    command: usr/bin/rnote
    extensions: [gnome]
    common-id: com.github.flxzt.rnote
    plugs:
      - home
      - removable-media
